name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT_ID }}
  PROJECT_NUMBER: ${{ secrets.GKE_PROJECT_NUMBER }}
  GKE_CLUSTER: n-test-cicd-cluster    # Add your cluster name here.
  GKE_ZONE: us-central1-c   # Add your cluster zone here.

jobs:
  job_id:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/${{ env.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/for-github-gke-auth/providers/githubactions'
        create_credentials_file: true
        service_account: 'nitin-gke-auth-sa@lucid-container-357617.iam.gserviceaccount.com'

    - uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}

    - name: 'get-deployments'
      shell: bash
      run: |
        kubectl get pods
        kubectl get deployment
